[package]
name = "wz"
version = "0.1.0"
repository = "https://github.com/broomstar/wz-rust"
description = "Native bindings to the libwz library"
edition = "2018"

[dependencies]
libz-sys = "1.1.2"

[build-dependencies]
bindgen = "0.57.0"
cc = "1.0"
