[package]
name = "wz"
version = "0.1.0"
links = "wz"
repository = "https://github.com/broomstar/wz-rust"
description = "Native bindings to the libwz library"

[dependencies]
libz-sys = ">= 0"
libc = "0.2"

[build-dependencies]
cmake = "0.1.2"
bindgen = "0.36.0"
